version: '2'

services:

  ldap:
    container_name: ldap
    image: mwaeckerlin/openldap
    env_file: .env
    ports:
      - '11010:389'
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_backups:/var/backups

  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    env_file: .env
    ports:
      - '11020:8080'
      - '11025:443'
    depends_on:
      - "ldap"
    volumes:
      - keycloak_config:/etc/keycloak

  admin:
    container_name: admin
    image: osixia/phpldapadmin
    env_file: .env
    ports:
      - '11030:80'
    depends_on:
      - "ldap"
    volumes:
      - admin_data:/var/lib/ldap
      - admin_config:/etc/ldap

volumes:

  keycloak_config:

  ldap_config:
  ldap_data:
  ldap_backups:

  admin_data:
  admin_config:

