version: '2'

services:

  openLDAP:
    container_name: openLDAP
    image: osixia/openldap
    env_file: .env
    ports:
      - '11010:389'
      - '11015:363'
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_backups:/var/backups

  phpLDAPadmin:
    container_name: phpLDAPadmin
    image: osixia/phpldapadmin
    env_file: .env
    ports:
      - '11020:80'
      - '11025:443'
    depends_on:
      - openLDAP
    volumes:
      - admin_data:/var/lib/ldap
      - admin_config:/etc/ldap

  Keycloak:
    container_name: Keycloak
    image: jboss/keycloak
    env_file: .env
    ports:
      - '11030:8080'
      - '11035:443'
    depends_on:
      - phpLDAPadmin
    volumes:
      - keycloak_config:/etc/keycloak


volumes:

  ldap_data:
  ldap_backups:

  admin_data:
  admin_config:

  keycloak_config:
