version: '3'

# Copy default.env to environment.env and change passwords.

services:

  app:
    container_name: tmi_access_token_auth
    image: jboss/keycloak:10.0.2
    restart: always
    ports:
      - '11000:8080'
      - '11005:443'
    volumes:
      - ./local/config/auth:/etc/auth
    depends_on:
      - db
    env_file:
      - environment.env

  db:
    container_name: tmi_access_token_db
    image: osixia/openldap:1.3.0
    restart: always
    ports:
      - '11010:389'
      - '11015:363'
    volumes:
      - ./local/data:/var/lib/ldap
      - ./local/config/ldap:/etc/ldap/slapd.d
      - ./local/backups:/var/backups
      - ./seed:/seed
    env_file:
      - environment.env

  admin:
    container_name: tmi_access_token_admin
    image: osixia/phpldapadmin:0.9.0
    restart: always
    ports:
      - '11020:80'
      - '11025:443'
    depends_on:
      - db
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=db
    env_file:
      - environment.env
