version: '2'

services:

  store:
    container_name: tmi_access_token
    image: osixia/openldap:1.3.0
    environment:
      - LDAP_ORGANISATION=TMI
      - LDAP_DOMAIN=tmi.mobi
      - LDAP_BASE_DN=dc=tmi,dc=mobi
      - LDAP_ADMIN_PASSWORD=change_me
      - LDAP_CONFIG_PASSWORD=change_me
    ports:
      - '11010:389'
      - '11015:363'
    volumes:
      - ./local/data:/var/lib/ldap
      - ./local/config/ldap:/etc/ldap/slapd.d
      - ./local/backups:/var/backups

  admin:
    container_name: tmi_access_token_admin
    image: osixia/phpldapadmin:0.9.0
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=store
      - PHPLDAPADMIN_HTTPS=false
    ports:
      - '11020:80'
      - '11025:443'
    depends_on:
      - store

  auth:
    container_name: tmi_access_token_auth
    image: jboss/keycloak:10.0.2
    environment:
      - KEYCLOAK_USER=CIA
      - KEYCLOAK_PASSWORD=change_me
    ports:
      - '11030:8080'
      - '11035:443'
    depends_on:
      - store
    volumes:
      - ./local/config/auth:/etc/auth
