version: '2'

services:

  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    env_file: .env
    ports:
      - '11080:8080'
      - '11443:443'
    depends_on:
      - "ldap"

  ldap:
    container_name: ldap
    build: ./build/openldap/image
    ports:
      - '11389:389'
      - '11636:636'
    volumes:
      - ldap_config:/etc/ldap/slapd.d
      - ldap_data:/var/lib/ldap

volumes:
  ldap_config:
  ldap_data: